name: scipion # you probably want to 'snapcraft register <name>'
base: core # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Cryo em image processing framework. Integration, traceability and analysis # 79 char long summary
description: >
  For STRUCTURAL BIOLOGIST: Scipion integrates existing software allowing you
  to smoothly switch from one package to another offering endless combinations.
  We started with single particle analysis (SPA) methods but we are currently
  expanding our toolset to include atomic modelling and tomography.
  For FACILITIES: Scipion will process your acquired images on the fly and will
  provide feedback to help you make decisions while the microscope is collecting
  data.
  For DEVELOPERS: A fast way to reach cryo em users and distribute your software
  Scipion is a plugin framework ready to discover new EM image processing
  software once you wrap it as a plugin.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  scipion:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .

apps:
    scipion:
      command: python3 -m scipion